# Generated by Django 5.1.7 on 2025-03-14 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default=None, max_length=150, verbose_name='Nombres')),
                ('apellido_materno', models.CharField(default=None, max_length=150, verbose_name='Apellidos materno ')),
                ('apellido_paterno', models.CharField(default=None, max_length=150, verbose_name='Apellido paterno ')),
                ('curp', models.CharField(default=None, max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(default=None, max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono celular')),
                ('telefono2', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Teléfono celular 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tipo', models.IntegerField(choices=[(10, 'LEAD'), (20, 'CLIENTE')], default=10, verbose_name='Tipo')),
                ('status', models.IntegerField(choices=[(10, 'ACTIVO'), (20, 'INACTIVO')], default=10, verbose_name='Status')),
                ('fecha_nacimiento', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de nacimiento')),
                ('created_at', models.IntegerField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.IntegerField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'permissions': [('can_view_cliente', 'VER CLIENTE'), ('can_update_cliente', 'ACTUALIZAR CLIENTE'), ('can_create_cliente', 'CREAR CLIENTE'), ('can_delete_cliente', 'ELIMINAR CLIENTE')],
            },
        ),
        migrations.CreateModel(
            name='DireccionClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente', to='clientes.cliente')),
                ('codigo_postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
            ],
        ),
    ]
